include $(CLEAR_VARS)
LOCAL_MODULE := GCMod
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := GCMod/MGC_6.2.030_platina_signed-brunorocha.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
LOCAL_OVERRIDES_PACKAGES := Snap Camera2 Camera
include $(BUILD_PREBUILT)